### ISSUE TITLE
react tags v5.x.x

### ISSUE THREAD

**Issue by mrdannael** [prakhar1989/react-tags#230]
### Features/Enhancements
- [ ] key code is deprecated (#196)
- [ ] custom tag component (#48, #211)
- [ ] tags inside 'input field' or default (#211, #132)
- [ ] choose to sort tags (#21) 
- [ ] inline styling (#45)
- [ ] should work with redux-form (#51)
- [ ] two react-tag-input in one place (#57, #173) 
- [ ] suggestions can be array of objects (#74, #131, #185)
- [ ] auto-add (#77)
- [ ] different options for input placement (#130)
- [ ] get rid of dnd or conditionally use dnd when needed (#141, #198)
- [ ] hide used suggestions (#171)
- [ ] optional submit button (#186)
- [ ] read-only tags (#194)
- [ ] setup eslint
- [ ] add storybook with examples
- [ ] setup semantic-release
- [ ] update docs
- [ ] release react-tags 5.x.x
### Bugs
- [ ] react-tags breaks other dnd's (#98)
--------
If you have any other requests feel free to write them down below. :beers:

**Comment by ad1992** [comment]
@mrdannael added pre commit hook in the list
